"""initial schema

Revision ID: ba3b919d6300
Revises: 
Create Date: 2026-05-02 09:40:48.314667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3b919d6300'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absence_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('crews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('source_workbook_version', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('row_counts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('task_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('full_display', sa.String(length=256), nullable=False),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('sponsor_person_id', sa.Integer(), nullable=True),
    sa.Column('orders_received', sa.Boolean(), nullable=False),
    sa.Column('itinerary_received', sa.Boolean(), nullable=False),
    sa.Column('aob_scheduled', sa.Boolean(), nullable=False),
    sa.Column('barracks_assigned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['sponsor_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persons_import_batch_id'), ['import_batch_id'], unique=False)

    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('validity_period_days', sa.Integer(), nullable=True),
    sa.Column('pinned_column', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_qualification_name')
    )
    with op.batch_alter_table('qualifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qualifications_import_batch_id'), ['import_batch_id'], unique=False)

    op.create_table('task_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('splittable', sa.Boolean(), nullable=False),
    sa.Column('reassignable', sa.Boolean(), nullable=False),
    sa.Column('carry_over_policy', sa.String(length=32), nullable=False),
    sa.Column('recurrence_rule', sa.JSON(), nullable=True),
    sa.Column('required_drivers_license', sa.Boolean(), nullable=False),
    sa.Column('required_duty_section', sa.Integer(), nullable=True),
    sa.Column('required_crew_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("carry_over_policy IN ('auto_same_person','auto_any_qualified','never','manual_prompt')", name='ck_task_carry_over_policy'),
    sa.ForeignKeyConstraint(['category_id'], ['task_categories.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['required_crew_id'], ['crews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_templates_import_batch_id'), ['import_batch_id'], unique=False)

    op.create_table('worklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_starting', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by_name', sa.String(length=128), nullable=True),
    sa.Column('amended_at', sa.DateTime(), nullable=True),
    sa.Column('amendment_reason', sa.Text(), nullable=True),
    sa.Column('operator_name', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['worklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worklists_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_worklists_week_starting'), ['week_starting'], unique=False)

    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['absence_codes.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.create_index('ix_absences_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_absences_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_absences_person_id'), ['person_id'], unique=False)

    op.create_table('crew_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crew_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crew_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crew_memberships_crew_id'), ['crew_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crew_memberships_person_id'), ['person_id'], unique=False)

    op.create_table('person_drivers_licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('has_license', sa.Boolean(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_drivers_licenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_drivers_licenses_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_drivers_licenses_person_id'), ['person_id'], unique=False)

    op.create_table('person_duty_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('duty_section', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_duty_sections', schema=None) as batch_op:
        batch_op.create_index('ix_person_duty_sections_current', ['person_id', 'valid_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_duty_sections_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_duty_sections_person_id'), ['person_id'], unique=False)

    op.create_table('person_prds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('prd_date', sa.Date(), nullable=False),
    sa.Column('change_reason', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_prds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_prds_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_prds_person_id'), ['person_id'], unique=False)

    op.create_table('person_quals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('qual_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('not_assigned','assigned','in_progress','qualified','dinq','expired','waived')", name='ck_person_qual_status'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['qual_id'], ['qualifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_quals', schema=None) as batch_op:
        batch_op.create_index('ix_person_quals_current', ['person_id', 'qual_id', 'valid_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_quals_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_quals_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_quals_qual_id'), ['qual_id'], unique=False)

    op.create_table('person_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.String(length=32), nullable=False),
    sa.Column('paygrade', sa.String(length=8), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_rates', schema=None) as batch_op:
        batch_op.create_index('ix_person_rates_current', ['person_id', 'valid_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_rates_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_rates_person_id'), ['person_id'], unique=False)

    op.create_table('person_roster_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('active','incoming','prd_pending','departed','dropped')", name='ck_roster_status_value'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_roster_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_roster_status_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_roster_status_person_id'), ['person_id'], unique=False)

    op.create_table('task_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('worklist_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.Column('carried_from_instance_id', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('open','in_progress','done','discarded','carried')", name='ck_task_instance_status'),
    sa.ForeignKeyConstraint(['carried_from_instance_id'], ['task_instances.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['task_categories.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['task_templates.id'], ),
    sa.ForeignKeyConstraint(['worklist_id'], ['worklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_instances_import_batch_id'), ['import_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_instances_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_instances_worklist_id'), ['worklist_id'], unique=False)

    op.create_table('task_template_required_quals',
    sa.Column('task_template_id', sa.Integer(), nullable=False),
    sa.Column('qual_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['qual_id'], ['qualifications.id'], ),
    sa.ForeignKeyConstraint(['task_template_id'], ['task_templates.id'], ),
    sa.PrimaryKeyConstraint('task_template_id', 'qual_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('task_instance_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('snoozed_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['task_instance_id'], ['task_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_person_id'), ['person_id'], unique=False)

    op.create_table('task_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('is_poic', sa.Boolean(), nullable=False),
    sa.Column('external_poic_name', sa.String(length=128), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.CheckConstraint('person_id IS NOT NULL OR external_poic_name IS NOT NULL', name='ck_assignment_has_subject'),
    sa.ForeignKeyConstraint(['instance_id'], ['task_instances.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assignments_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index('ux_one_poic_per_instance', ['instance_id'], unique=True, sqlite_where=sa.text('is_poic = 1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.drop_index('ux_one_poic_per_instance', sqlite_where=sa.text('is_poic = 1'))
        batch_op.drop_index(batch_op.f('ix_task_assignments_instance_id'))

    op.drop_table('task_assignments')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_person_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    op.drop_table('task_template_required_quals')
    with op.batch_alter_table('task_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_instances_worklist_id'))
        batch_op.drop_index(batch_op.f('ix_task_instances_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_task_instances_import_batch_id'))

    op.drop_table('task_instances')
    with op.batch_alter_table('person_roster_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_roster_status_person_id'))
        batch_op.drop_index(batch_op.f('ix_person_roster_status_import_batch_id'))

    op.drop_table('person_roster_status')
    with op.batch_alter_table('person_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_rates_person_id'))
        batch_op.drop_index(batch_op.f('ix_person_rates_import_batch_id'))
        batch_op.drop_index('ix_person_rates_current')

    op.drop_table('person_rates')
    with op.batch_alter_table('person_quals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_quals_qual_id'))
        batch_op.drop_index(batch_op.f('ix_person_quals_person_id'))
        batch_op.drop_index(batch_op.f('ix_person_quals_import_batch_id'))
        batch_op.drop_index('ix_person_quals_current')

    op.drop_table('person_quals')
    with op.batch_alter_table('person_prds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_prds_person_id'))
        batch_op.drop_index(batch_op.f('ix_person_prds_import_batch_id'))

    op.drop_table('person_prds')
    with op.batch_alter_table('person_duty_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_duty_sections_person_id'))
        batch_op.drop_index(batch_op.f('ix_person_duty_sections_import_batch_id'))
        batch_op.drop_index('ix_person_duty_sections_current')

    op.drop_table('person_duty_sections')
    with op.batch_alter_table('person_drivers_licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_drivers_licenses_person_id'))
        batch_op.drop_index(batch_op.f('ix_person_drivers_licenses_import_batch_id'))

    op.drop_table('person_drivers_licenses')
    with op.batch_alter_table('crew_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crew_memberships_person_id'))
        batch_op.drop_index(batch_op.f('ix_crew_memberships_crew_id'))

    op.drop_table('crew_memberships')
    with op.batch_alter_table('absences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_absences_person_id'))
        batch_op.drop_index(batch_op.f('ix_absences_import_batch_id'))
        batch_op.drop_index('ix_absences_dates')

    op.drop_table('absences')
    with op.batch_alter_table('worklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worklists_week_starting'))
        batch_op.drop_index(batch_op.f('ix_worklists_import_batch_id'))

    op.drop_table('worklists')
    with op.batch_alter_table('task_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_templates_import_batch_id'))

    op.drop_table('task_templates')
    with op.batch_alter_table('qualifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qualifications_import_batch_id'))

    op.drop_table('qualifications')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persons_import_batch_id'))

    op.drop_table('persons')
    op.drop_table('task_categories')
    op.drop_table('settings')
    op.drop_table('import_batches')
    op.drop_table('crews')
    op.drop_table('absence_codes')
    # ### end Alembic commands ###
